[package]
name = "winapi-tlb-bindgen"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
clap = "2.21.x"
winapi = { git = "https://github.com/retep998/winapi-rs/", rev = "96c9334207e0cf0b8da535455e29eda46d675bbb", features = ["objbase", "oleauto", "winerror"] }

[profile.dev]
panic = "abort"
