[package]
name = "winapi-tlb-bindgen"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.x", features = ["objbase", "oleauto", "winerror"] }
