[package]
name = "winapi-tlb-bindgen"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
clap = "2.23.x"
derive-error-chain = "0.11.x"
error-chain = "0.11.x"
winapi = { version = "0.3.x", features = ["objbase", "oleauto", "winerror"] }

[profile.dev]
panic = "abort"
