[package]
name = "winapi-tlb-bindgen-bin"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
clap = "2.31.x"
winapi-tlb-bindgen = { version = "0.1.x", path = "../" }

[profile.dev]
panic = "abort"
