[package]
name = "winapi-tlb-bindgen-bin"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
winapi-tlb-bindgen = { version = "0.1.x", path = "../" }
