[package]
name = "winapi-tlb-bindgen-bin"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"

[dependencies]
structopt = "0.2"
winapi-tlb-bindgen = { version = "0.1.x", path = "../" }
